# File Limits
MAX_MERGE_FILES = 20
MAX_DELETE_FILES = 1
MAX_SPLIT_FILES = 1
# Temp Folders
MERGE_TEMP_FOLDER = "merge_temp_files"
DELETE_TEMP_FOLDER = "page_editor_temp"
SPLIT_TEMP_FOLDER = "split_temp"
FILE_PICKER_DEFAULT_FOLDER = "temp_uploads"
# Output Names
MERGED_OUTPUT_NAME = "merged_result.pdf"
EDITED_OUTPUT_PREFIX = "edited_"
# Window Settings
MAIN_WINDOW_TITLE = "PDF Master Suite"
MAIN_WINDOW_START_WIDTH = 1200
MAIN_WINDOW_START_HEIGHT = 800
MAIN_WINDOW_MIN_WIDTH = 900
MAIN_WINDOW_MIN_HEIGHT = 700
STYLESHEET = "assets/styles.qss"
# Headers
MERGE_HEADER_TITLE = "Merge PDF Documents"
SPLIT_HEADER_TITLE = "Split PDF"
# Dashboard Cards
TOOL_CARD_WIDTH = 350
TOOL_CARD_HEIGHT = 250
# Sidebar Dimensions
SIDEBAR_WIDTH = 400
SIDEBAR_WIDTH_SPLIT = 460
# Preview Components
RANGE_GROUP_SIZE = 200
PAGE_THUMB_WIDTH = 70
PAGE_THUMB_HEIGHT = 92
# Button Dimensions
ADD_BUTTON_SIZE = 44
PARITY_BUTTON_HEIGHT = 52
PARITY_BUTTON_WIDTH = 96
MODE_BUTTON_HEIGHT = 90
PRIMARY_BUTTON_HEIGHT = 56
# Input Dimensions
PAGES_INPUT_HEIGHT = 45
# File Card Dimensions
FILE_CARD_WIDTH = 160
FILE_CARD_HEIGHT = 220
CARD_NUMBER_LABEL_SIZE = 24
CARD_NAME_LABEL_HEIGHT = 30
CARD_ACTION_BUTTON_SIZE = 30
# Header Bar Dimensions
HEADER_BAR_HEIGHT = 70
BACK_BUTTON_SIZE = 50
# File Picker Dialog
FILE_PICKER_WIDTH = 400
FILE_PICKER_HEIGHT = 220
# Password Dialog
PASSWORD_DIALOG_WIDTH = 450
PASSWORD_DIALOG_HEIGHT = 300
