MAX_MERGE_FILES = 20
MAX_DELETE_FILES = 1
MAX_SPLIT_FILES = 1
MERGE_TEMP_FOLDER = "merge_temp_files"
DELETE_TEMP_FOLDER = "page_editor_temp"
SPLIT_TEMP_FOLDER = "split_temp"
FILE_PICKER_DEFAULT_FOLDER = "temp_uploads"
MERGED_OUTPUT_NAME = "merged_result.pdf"
EDITED_OUTPUT_PREFIX = "edited_"
MAIN_WINDOW_TITLE = "PDF Master Suite"
MAIN_WINDOW_START_WIDTH = 1200
MAIN_WINDOW_START_HEIGHT = 800
MAIN_WINDOW_MIN_WIDTH = 900
MAIN_WINDOW_MIN_HEIGHT = 700
STYLESHEET = "assets/styles.qss"
MERGE_HEADER_TITLE = "Merge PDF Documents"
SPLIT_HEADER_TITLE = "Split PDF"
TOOL_CARD_WIDTH = 350
TOOL_CARD_HEIGHT = 250
SIDEBAR_WIDTH = 400
SIDEBAR_WIDTH_SPLIT = 460
RANGE_GROUP_SIZE = 200
PAGE_THUMB_WIDTH = 70
PAGE_THUMB_HEIGHT = 92
ADD_BUTTON_SIZE = 44
PARITY_BUTTON_HEIGHT = 52
PARITY_BUTTON_WIDTH = 96
MODE_BUTTON_HEIGHT = 90
PRIMARY_BUTTON_HEIGHT = 56
PAGES_INPUT_HEIGHT = 45
FILE_CARD_WIDTH = 160
FILE_CARD_HEIGHT = 220
CARD_NUMBER_LABEL_SIZE = 24
CARD_NAME_LABEL_HEIGHT = 30
CARD_ACTION_BUTTON_SIZE = 30
HEADER_BAR_HEIGHT = 70
BACK_BUTTON_SIZE = 50
FILE_PICKER_WIDTH = 400
FILE_PICKER_HEIGHT = 220
PASSWORD_DIALOG_WIDTH = 450
PASSWORD_DIALOG_HEIGHT = 300

SPLIT_SIZE_MIN_KB = 10
SPLIT_SIZE_MAX_MB = 1024
SPLIT_SIZE_SAFETY_MARGIN = 0.95
MAX_SPLIT_OUTPUT_FILES = 500

INPUT_VALIDATION_DELAY_MS = 1000

CLEANUP_RETRY_ATTEMPTS = 3
CLEANUP_RETRY_DELAY_SEC = 0.3

FILENAME_TRUNCATE_LIMIT = 20

GRID_MIN_COLUMNS = 1
GRID_CARD_SPACING = 20
GRID_CONTAINER_PADDING = 40
GRID_MIN_FALLBACK_WIDTH = 1000

THUMBNAIL_DEFAULT_WIDTH = 150
THUMBNAIL_DEFAULT_HEIGHT = 145
