MERGE_MAX_FILES = 20
DELETE_MAX_FILES = 1

MERGE_TEMP_FOLDER = "merge_temp_files"
DELETE_TEMP_FOLDER = "page_editor_temp"
FILE_PICKER_DEFAULT_FOLDER = "temp_uploads"

MERGED_OUTPUT_NAME = "merged_result.pdf"
EDITED_OUTPUT_PREFIX = "edited_"

MAIN_WINDOW_TITLE = "PDF Master Suite"
MAIN_WINDOW_WIDTH = 1000
MAIN_WINDOW_HEIGHT = 700

STYLESHEET_MAIN = "assets/style_app.qss"
STYLESHEET_TOOLS = "assets/style.qss"

MERGE_HEADER_TITLE = "Merge PDF Documents"

PDF_GRID_MAX_ITEMS_DELETE = 2000
PDF_GRID_MAX_ITEMS_MERGE = 5

TOOL_CARD_WIDTH = 300
TOOL_CARD_HEIGHT = 240

FILE_DIALOG_MAX_FILES_MERGE = 20
FILE_DIALOG_MAX_FILES_DELETE = 1
